[project]
name = "dic"
version = "0.1.0"
description = "a minimalist CLI for chat LLMs"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
dic = "dic.dic:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dic", "dic.adaptors"]
include-package-data = true

[tool.setuptools.package-data]
dic = ["models.json"]
